import h5py, healpy, pyfits
import numpy as np
import sys
import subprocess 
import os
from matplotlib import pyplot as plt

def Healpix2Cartesian(basedir, fname):                        
    # Read from hdf5 file
    os.chdir(basedir)
    f = h5py.File(basedir+'/'+fname,'r')
    
    for t in f['templates/']:
        
        if t in ["energies",'pi0_0','brem_0','ics_opt']: 
            continue
        print "Writing", t
        
        # Get the cartesian maps for each energy
        hpixcube = f['templates/'+t][()]
        if t=='ics_fir':
            hpixcube+=f['templates/ics_fir'][()]


        cartcube = np.zeros((hpixcube.shape[0], 721,1440), dtype=np.float32)
        for i in range(hpixcube.shape[0]):
            cartcube[i] = healpy.cartview(hpixcube[i], hold=True, return_projected_map=True,
                                                  xsize=1440, lonra=[-179.875, 179.875],flip='geo')
            plt.gcf()
        
        # Generate new hdu object
        hdu_new = pyfits.PrimaryHDU(cartcube.astype(np.float32))
        

        # Copy galdef into header
        galdef = dict(f['/galdef'].attrs.items())
        hdu_new.header.add_comment("Diffuse model generated by Eric Carlson (erccarls@ucsc.edu)")
        for key, val in galdef.items():
            hdu_new.header.add_comment(key + "=" +val)
        
        hdu_new.header['CRVAL1'] = 0.0
        hdu_new.header['CRPIX1'] = 720
        hdu_new.header['CDELT1'] = 0.25
        hdu_new.header['CUNIT1']= 'deg'
        hdu_new.header['CTYPE1']= 'GLON-CAR'
        hdu_new.header['CRVAL2'] = 0
        hdu_new.header['CRPIX2'] = 361
        hdu_new.header['CDELT2'] = 0.25
        hdu_new.header['CUNIT2']= 'deg'
        hdu_new.header['CTYPE2']= 'GLAT-CAR'
        hdu_new.header['CRVAL3'] = float(galdef['E_gamma_min'])
        hdu_new.header['CRPIX3'] = 0
        hdu_new.header['CDELT3'] = np.log10(float(galdef['E_gamma_factor']))
        hdu_new.header['CTYPE3']= 'Energy'
        hdu_new.header['CUNIT3']= 'MeV'
        hdu_new.header['EXTEND']=True
        hdu_new.header['CREATOR'] = ('Eric Carlson (erccarls@ucsc.edu)', '')

        # Write energy extension table
        energies = np.array([50*float(galdef['E_gamma_factor'])**i for i in range(cartcube.shape[0])])
        tbhdu = pyfits.BinTableHDU.from_columns([
                pyfits.Column(name='Energy', format='D', array=energies),])
        tbhdu.header['EXTNAME']="ENERGIES"
        
        hdulist = pyfits.HDUList([hdu_new,tbhdu])
        
        # Write to file
        if t=='ics_fir':
            fname_out = fname.split('.')[0]+"_ics_opt_fir_mapcube.fits"
        else: 
            fname_out = fname.split('.')[0]+"_"+t+"_mapcube.fits"
        hdulist.writeto(basedir+'/'+fname_out,clobber=True)

        # For some reason on my platform, pyfits gzip compression was writing corrupt files.
        p = subprocess.Popen(['gzip ' + basedir+'/'+fname_out ,], shell=True)
        
if __name__ == "__main__": 
    basedir, fname = sys.argv[1], sys.argv[2]
    Healpix2Cartesian(basedir, fname)